[package]
name = "x25519_diffie_hellman_aes_256_gbc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes-gcm = "0.10.3"
rand_core = "0.6.4"
x25519-dalek = "2.0.0"
